on: push
name: Try my own image 
jobs:
  my_job:
    container: 2dii/pacta_analysis:latest
    runs-on: ubuntu-latest
    env:
      MYVAR: myva
    steps:
      - name: Query dependencies
        run: |
          echo "Rscript 'row.names(installed.packages())'
