on: push
name: Try my own image 
jobs:
  my_job:
    container: 2dii/pacta_analysis:latest
    runs-on: ubuntu-latest
    steps:
      - name: Query installed packages 
        run: |
          echo "Rscript 'row.names(installed.packages())'"
