on: push
name: Try my own image 
jobs:
  my_job:
    container: rocker/verse
    runs-on: ubuntu-latest
    env:
      MYVAR: myva
    steps:
      - name: Query dependencies
        run: |
          echo "$MYVAR"
          echo "Rscript 'row.names(installed.packages())'
